Parameters:
  LambdaArtifactBucketName:
    Type: String
    Default: befit-artifact
  S3BucketName:
    Type: String
    Default: rutwik-b00934537-images
  DynamoTableName:
    Type: String
    Default: LabelsTable

Resources:
  ExampleS3:
    Type: AWS::S3::Bucket
    DependsOn: ExampleInvokePermission
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: png
            Function: !GetAtt [ ExampleLambdaFunction, Arn]

  ExampleInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: ExampleLambdaFunction
    Properties:
      FunctionName:
        Fn::GetAtt:
          - ExampleLambdaFunction
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${S3BucketName}

  ExampleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: rutwik-b00934537
        S3Key: rutwik-b00934537-code.zip
      FunctionName: rutwik-test-lambda-function
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::768859185732:role/LabRole
      Runtime: python3.10
      Timeout: 123

  SecondLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: second_lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri:
        Bucket: 'rutwik-b00934537'
        Key: 'second-lambda-function.zip'
      Events:
        SecondApi:
          Type: Api
          Properties:
            Path: /second-path
            Method: GET

  SecondApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title: !Ref SecondLambdaFunction
        paths:
          /second-path:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecondLambdaFunction.Arn}/invocations
              responses: {}

  Outputs:
    SecondApiURL:
      Description: 'API endpoint URL for Prod stage'
      Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/second-path/'


  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageKey
          AttributeType: S
      KeySchema:
        - AttributeName: ImageKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref DynamoTableName

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MyEmailSNS
      TopicName: MyEmailSNS
      Subscription:
        - Protocol: email
          Endpoint: "rbs29012000@gmail.com"

  Ec2keyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: rutvik-b00934537-key-pair
      KeyType: rsa

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90
      InstanceType: t2.micro
      KeyName: !Ref Ec2keyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update
          sudo apt-get install -y
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          cd /home/ubuntu/
          echo 'REACT_APP_IMAGE_RECOGNITION_URL="https://${SecondApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"' > .env
          git clone https://github.com/rbshah29/cloud-project.git
          cd cloud-project
          sudo pip3 install -r requirements.txt
          python3 main.py
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0