Parameters:
  LambdaArtifactBucketName:
    Type: String
    Default: befit-artifact
  S3BucketName:
    Type: String
    Default: rutwik-b00934537-images
  DynamoTableName:
    Type: String
    Default: LabelsTable

Resources:
  ExampleS3:
    Type: AWS::S3::Bucket
    DependsOn: ExampleInvokePermission
    Properties:
      BucketName: !Ref S3BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: png
            Function: !GetAtt [ ExampleLambdaFunction, Arn]

  ExampleInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: ExampleLambdaFunction
    Properties:
      FunctionName:
        Fn::GetAtt:
          - ExampleLambdaFunction
          - Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:s3:::${S3BucketName}

  ExampleLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: rutwik-b00934537
        S3Key: rutwik-b00934537-code.zip
      FunctionName: rutwik-test-lambda-function
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::768859185732:role/LabRole
      Runtime: python3.10
      Timeout: 123

  SecondLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: rutwik-b00934537
        S3Key: apiGateway.zip
      FunctionName: rutwik-second-lambda-function
      Handler: lambda.lambda_handler
      Role: arn:aws:iam::768859185732:role/LabRole
      Runtime: python3.10
      Timeout: 123

  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApi

  MyApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref MyApi
      ParentId: !GetAtt 
        - MyApi
        - RootResourceId
      PathPart: secondAPI

  MyApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref MyApi
      ResourceId: !Ref MyApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecondLambdaFunction.Arn}/invocations
        IntegrationResponses:
          - StatusCode: 200
        PassthroughBehavior: WHEN_NO_MATCH
      MethodResponses:
        - StatusCode: 200

  ExtractApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - MyApiMethod
    Properties:
      RestApiId: !Ref MyApi
      StageName: prod

  PermissionForApiToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt 
        - SecondLambdaFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApi}/*/*

  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ImageKey
          AttributeType: S
      KeySchema:
        - AttributeName: ImageKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref DynamoTableName

  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MyEmailSNS
      TopicName: MyEmailSNS
      Subscription:
        - Protocol: email
          Endpoint: "rbs29012000@gmail.com"

  Ec2keyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: rutvik-b00934537-key-pair
      KeyType: rsa

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90
      InstanceType: t2.micro
      KeyName: !Ref Ec2keyPair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo apt-get update
          sudo apt-get install -y
          sudo apt-get install -y git
          sudo apt-get install -y python3-pip
          cd /home/ubuntu/
          git clone https://github.com/rbshah29/cloud-project.git
          echo 'api_gateway="https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/secondAPI"' > api.py
          cd cloud-project
          sudo pip3 install -r requirements.txt
          python3 main.py
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
